/** Chart/UI colors keyed by expense category name (frontend only). */
export const EXPENSE_CATEGORY_COLORS = {
  "Food & Groceries": { color: "#F59E0B", hoverColor: "#D97706" },
  Transport: { color: "#3B82F6", hoverColor: "#2563EB" },
  Housing: { color: "#8B5CF6", hoverColor: "#7C3AED" },
  "Bills & Utilities": { color: "#06B6D4", hoverColor: "#0891B2" },
  Shopping: { color: "#EC4899", hoverColor: "#DB2777" },
  Health: { color: "#10B981", hoverColor: "#059669" },
  Entertainment: { color: "#F97316", hoverColor: "#EA580C" },
  "Education & Work": { color: "#6366F1", hoverColor: "#4F46E5" },
  Personal: { color: "#14B8A6", hoverColor: "#0D9488" },
  Finance: { color: "#EF4444", hoverColor: "#DC2626" },
  "Family & Social": { color: "#A855F7", hoverColor: "#9333EA" },
  "Savings & Investments": { color: "#22C55E", hoverColor: "#16A34A" },
  Other: { color: "#9CA3AF", hoverColor: "#6B7280" },
};

export const SUBCATEGORY_ICONS = {
  Groceries: "🛒",
  Restaurants: "🍽️",
  "Cafe & Snacks": "☕",
  "Food Delivery": "🛵",
  "Milk & Dairy": "🥛",
  Fuel: "⛽",
  "Cab & Auto": "🚕",
  "Public Transit": "🚌",
  Parking: "🅿️",
  "Vehicle Maintenance": "🔧",
  Rent: "🏠",
  "Home Maintenance": "🛠️",
  "Household Items": "🧹",
  Electricity: "💡",
  Internet: "📶",
  "Mobile Recharge": "📱",
  "Water & Gas": "🚿",
  "DTH & Cable": "📺",
  Clothes: "👕",
  Electronics: "💻",
  "Online Shopping": "📦",
  "Home & Decor": "🛋️",
  Medicines: "💊",
  "Doctor & Clinic": "🩺",
  Fitness: "🏋️",
  "Insurance (Health)": "🏥",
  "Movies & Events": "🎬",
  Subscriptions: "📺",
  Games: "🎮",
  Outing: "🎉",
  Courses: "📚",
  Books: "📖",
  "Software & Tools": "🧠",
  "Office / Co-working": "🏢",
  "Salon & Grooming": "💇",
  "Personal Care": "🧴",
  Laundry: "👔",
  "Credit Card Payment": "💳",
  "EMI / Loan": "🏦",
  "Bank Charges": "🏧",
  "Insurance (Life/Other)": "📄",
  Gifts: "🎁",
  Donations: "🤝",
  "Family Support": "👨‍👩‍👧",
  "Savings Transfer": "💰",
  "Mutual Funds": "📈",
  Stocks: "📊",
  "Fixed Deposit": "🔒",
  Miscellaneous: "🗂️",
  "Petty Cash": "🪙",
  Uncategorized: "❓",
  "Monthly Salary": "💼",
  Bonus: "💲",
  Overtime: "⏰",
  Freelance: "🧑‍💻",
  "Client Payment": "🤝",
  "Business Income": "🏪",
  Dividends: "🧾",
  Interest: "💹",
  "Capital Gains": "📉",
  Refund: "🔁",
  Cashback: "💸",
  Reimbursement: "🔙",
  "Gift Received": "🎀",
  "Family Transfer": "↔️",
  "Rental Income": "🏡",
  Other: "🔖",
};
